export default {
  products: [
    {
      _id: 1,
      name: "Slim Shirt Men",
      category: "Shirt",
      image: "/images/d1.jpg",
      price: 60,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Totam dolorum dolores adipisci? Debitis dolor, aut quo, officiis, nisi nobis porro dicta tenetur magnam blanditiis itaque sint cupiditate pariatur distinctio consequuntur.",
      countInStock: 10,
    },
    {
      _id: 2,
      name: "Kemeja Bagus",
      category: "Shirt",
      image: "/images/d1.jpg",
      price: 60,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Totam dolorum dolores adipisci? Debitis dolor, aut quo, officiis, nisi nobis porro dicta tenetur magnam blanditiis itaque sint cupiditate pariatur distinctio consequuntur.",
      countInStock: 4,
    },
    {
      _id: 3,
      name: "Kemeja Hitam",
      category: "Shirt",
      image: "/images/d1.jpg",
      price: 60,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Totam dolorum dolores adipisci? Debitis dolor, aut quo, officiis, nisi nobis porro dicta tenetur magnam blanditiis itaque sint cupiditate pariatur distinctio consequuntur.",
      countInStock: 5,
    },
    {
      _id: 4,
      name: "Slim Shirt Men",
      category: "Shirt",
      image: "/images/d1.jpg",
      price: 60,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Totam dolorum dolores adipisci? Debitis dolor, aut quo, officiis, nisi nobis porro dicta tenetur magnam blanditiis itaque sint cupiditate pariatur distinctio consequuntur.",
      countInStock: 5,
    },
    {
      _id: 5,
      name: "Slim Shirt Men",
      category: "Shirt",
      image: "/images/d1.jpg",
      price: 60,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Totam dolorum dolores adipisci? Debitis dolor, aut quo, officiis, nisi nobis porro dicta tenetur magnam blanditiis itaque sint cupiditate pariatur distinctio consequuntur.",
      countInStock: 5,
    },
    {
      _id: 6,
      name: "Slim Shirt Men",
      category: "Shirt",
      image: "/images/d1.jpg",
      price: 60,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Totam dolorum dolores adipisci? Debitis dolor, aut quo, officiis, nisi nobis porro dicta tenetur magnam blanditiis itaque sint cupiditate pariatur distinctio consequuntur.",
      countInStock: 5,
    },
    {
      _id: 7,
      name: "Slim Shirt Men",
      category: "Shirt",
      image: "/images/d1.jpg",
      price: 60,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Totam dolorum dolores adipisci? Debitis dolor, aut quo, officiis, nisi nobis porro dicta tenetur magnam blanditiis itaque sint cupiditate pariatur distinctio consequuntur.",
      countInStock: 5,
    },
    {
      _id: 8,
      name: "Slim Shirt Men",
      category: "Shirt",
      image: "/images/d1.jpg",
      price: 60,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Totam dolorum dolores adipisci? Debitis dolor, aut quo, officiis, nisi nobis porro dicta tenetur magnam blanditiis itaque sint cupiditate pariatur distinctio consequuntur.",
      countInStock: 5,
    },
  ],
};
